---
kind: ReplicationController
apiVersion: v1
metadata:
  name: hello-rc2
spec:
  replicas: 2
  selector:
    app: hello-world2
  template:
    metadata:
      labels:
        app: hello-world2
    spec:
      containers:
      - name: hello-ctr2
        image: nigelpoulton/pluralsight-docker-ci
        ports:
        - containerPort: 8080
