FROM mcr.microsoft.com/dotnet/core/aspnet:3.1 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1 AS build
WORKDIR /src
COPY ["mycorekube.csproj",""]
RUN dotnet restore "./mycorekube.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "mycorekube.csproj" -c Release -o /app/build

FROM build AS publish
RUN  dotnet publish "mycorekube.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "mycorecube.dll"]